### ISSUE TITLE
this.recaptcha.execute is not a function

### ISSUE THREAD

**Issue by yss14** [szchenghuang/react-google-invisible-recaptcha#1] opened 2017-05-11 13:06 UTC
If I implement your example in my project, it says that the reference stored in `this.recaptcha` has no `execute()` function. If I log the reference object, there is really no property `execute` and also no property `reset` or `getResponse`.

```
import Recaptcha from 'react-google-invisible-recaptcha';

<Recaptcha ref={ref => this.recaptcha = ref} sitekey="<mykey>" onResolved={this.onResolved.bind(this)} />

onSubmit(e) {
        e.preventDefault();
        console.dir(this.recaptcha)
        this.recaptcha.execute();
}

onResolved() {
        alert('Recaptcha resolved with response: ' + this.recaptcha.getResponse());
}
```

<img width="550" alt="bildschirmfoto 2017-05-11 um 15 05 20" src="https://cloud.githubusercontent.com/assets/4346842/25950454/56926500-365b-11e7-8d63-41ebf728af22.png">

**Comment by szchenghuang** [comment] 2017-05-12 02:29
Thank you for reporting, @yss14.

Could you show a minimum complete component which I can replicate to reproduce the issue?

The example disclosed in README is a working demo ([src](https://github.com/szchenghuang/react-google-invisible-recaptcha/blob/master/example/index.js)) which can be referenced.

**Comment by delx** [comment] 2017-08-07 08:19
I had the same issue. It happened, because I had a script tag in my HTML markup which loaded the Google Recaptcha JS:
`<script src="https://www.google.com/recaptcha/api.js?hl=it" async defer></script>`

**Comment by szchenghuang** [comment] 2017-08-13 14:10
@delx, I don't think the script should be loaded multiple times. It will be problematic. Will it work if you don't explicitly load the script?

What is the particular reason to explicitly load the script when this module implicitly loads one for you?

**Comment by billzhong** [comment] 2018-01-10 12:03
Hi,

I had same error, the demo doesn't work either.

```
bundle.js:1089 Uncaught TypeError: this.recaptcha.execute is not a function
    at Form.onSubmit (bundle.js:1089)
    at HTMLUnknownElement.callCallback (bundle.js:4526)
    at Object.invokeGuardedCallbackDev (bundle.js:4565)
    at Object.invokeGuardedCallback (bundle.js:4422)
    at Object.invokeGuardedCallbackAndCatchFirstError (bundle.js:4436)
    at executeDispatch (bundle.js:4659)
    at Object.executeDispatchesInOrder (bundle.js:4681)
    at executeDispatchesAndRelease (bundle.js:5196)
    at executeDispatchesAndReleaseTopLevel (bundle.js:5207)
    at Array.forEach (<anonymous>)
```

Test at Chrome for OSX, version  63.0.3239.132.

**Comment by szchenghuang** [comment] 2018-01-10 14:09
Confirmed. This issued can be reproduced on my side either.

Thanks for bringing this up @billzhong. It will be fixed soon.

**Closed** 2018-01-10 14:21 UTC
